//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAPI_and_MVC_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address_Line1 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Post_Code { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
    }
}
